### ISSUE TITLE
Hitting blank page on tool directory link after activation

### ISSUE THREAD

**Issue by mkgold** [cuny-academic-commons/dirt-directory-client#7]
I'm having a problem with the new DiRT plugin. Here is what is happening:

I added the DiRT Directory client to NYCDH, a multisite install running CBOX

I network activated the plugin

once network activated, I saw "Digital Research Tools" in the sidebar of a group

I clicked on it and saw a link to "Explore more tools from DiRT on the Digital Tools Directory." The link went here - http://nycdh.org/tool/

When I clicked on the link, I hit a blank page

--

Flushing permalinks (going to Dashboard > Settings > Permalinks and resaving existing options did not fix the issue

**Comment by boonebgorges** [comment]
If you're running cbox-theme or a derivative thereof, try creating a directory in your theme called 'dirt' and put the following file into it: https://raw.githubusercontent.com/cuny-academic-commons/dirt-directory-client/1.0.x/templates/dirt/non-theme-compat-index.php

**Comment by mkgold** [comment]
Hi Boone,

Finally had time to try this but I am still hitting a blank page - http://nycdh.org/tool/

I put the "dirt" folder with that PHP file in wp-content/themes/cbox-theme

**Comment by boonebgorges** [comment]
Hm, I'm not sure. The next version of the cbox-theme will have native support for dirt-directory-client. Maybe you can wait until the upgrade to see if it solves the problem for you?

**Comment by mkgold** [comment]
Sure. Thanks.

**Comment by mkgold** [comment]
Drat. Just upgraded and it didn't fix the issue . . .

**Comment by boonebgorges** [comment]
You updated the theme too? I think that's a separate step.

**Comment by mkgold** [comment]
No, I didn't. Thanks. Theme updated failed, though - "An error occurred
while updating Commons In A Box: Could not remove the old theme."

**Comment by boonebgorges** [comment]
Who set up this site? It's possible that your cbox-theme is a git checkout.

**Comment by mkgold** [comment]
I set up the site . . . I think I activated the theme through the dashboard, Thinking I should delete the theme files and re-add through FTP?

**Comment by boonebgorges** [comment]
I guess so. It seems like a file permissions problem.

**Comment by mkgold** [comment]
Thanks, Boone. Sorry to ask, but do I just download a zip of this -
https://github.com/cuny-academic-commons/cbox-theme -- and upload it to the
current cbox theme folder after deleting what is there?

**Comment by boonebgorges** [comment]
Yes. Delete wp-content/themes/cbox-theme. Upload the unzipped folder, 
and make sure it's named cbox-theme.

**Comment by mkgold** [comment]
That worked!! http://nycdh.org/tool/

(even if I did have to reset many elements of the homepage layout/widgets/etc. Worth it!!)

**Comment by boonebgorges** [comment]
Cool!

**Comment by mkgold** [comment]
Thanks for bearing with me and for all of your help
